name: Integration tests
on:
  pull_request: {}
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - master
jobs:
  kind_integration_tests:
    name: KinD integration tests
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup KinD
      uses: engineerd/setup-kind@v0.4.0
      with:
        version: v0.8.1
    - name: Docker build
      run: |
        docker build -t gcr.io/linkerd-io/proxy-init:latest .
        docker build -t buoyantio/iptables-tester:v1 -f integration_test/iptables/Dockerfile-tester ./integration_test
    - name: Load image into the local KinD cluster
      run: |
        kind load docker-image gcr.io/linkerd-io/proxy-init:latest
        kind load docker-image buoyantio/iptables-tester:v1
    - name: Run integration tests
      run: |
        cd integration_test
        ./run_tests.sh
  arm64_integration_tests:
    name: ARM64 integration tests
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run integration tests with k3s cluster using QEMU
      uses: uraimo/run-on-arch-action@v1.0.9
      with:
        architecture: aarch64
        distribution: ubuntu18.04
        run: |
          apt-get update && apt-get install -y curl
          curl -fsSL https://get.docker.com | sh -
          curl -s https://raw.githubusercontent.com/rancher/k3d/master/install.sh | bash
          docker images
          k3d create cluster k3s-proxy-init
          kubectl get nodes
          kubectl get pods --all-namespaces
          ls -al
          pwd
